### ISSUE TITLE
What if storage goes down ?

### ISSUE THREAD

**Issue by mlmarius** [vieux/docker-volume-sshfs#34]
Hi.

I am testing the plugin and when the storage provider goes down, the volume inside the docker container disappears but it never reappears if the storage provider comes back up. How can this be handled ?

**Comment by vieux** [comment]
@mlmarius do you have a step by step way to reproduce ?

**Comment by mlmarius** [comment]
I am running this stack on a 2 node swarm:

```
version: "3"
services:
    bash:
        image: bash
        entrypoint: /usr/local/bin/bash
        volumes:
            - sshvol1:/sshvol1
        deploy:
            mode: global

        stdin_open: true
        tty: true


volumes:
    sshvol1:
        driver: vieux/sshfs
        driver_opts:
            sshcmd: user@ssh-host:/path/to/sshvol
```

Then I briefly stop ssh-host and restart it. When ssh-host goes down the volume is unmounted from the containers but when ssh-host comes back up or is reachable again the volume does not reappear on the containers.
