### ISSUE TITLE
sshfs mount with docker-compose for a service

### ISSUE THREAD

**Issue by ucyo** [vieux/docker-volume-sshfs#48]
I can not mount the volume in an service environment `docker-compose.yml` file. Everything works fine per command line.

I created the volume:
```bash
# sudo docker volume create -d vieux/sshfs -o sshcmd=<sshcmd> -o allow_other sshvolume
````
And starting via cli works:
```bash
# sudo docker run -p 8080:8080 -v sshvolume:/path/to/folder --name vieux-test someimage
```

If I want to start the same container as a docker service the application is not running. I tried following `docker-compose.yml` version:

```yaml
version: "3.4"

services:
    thredds:
        image: someimage
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: ".1"
                    memory: 2G
            restart_policy:
                condition: on-failure
        ports:
            - "8080:8080"
        volumes:
            - sshvolume:/path/to/folder
        networks:
            - fancynet

volumes:
    sshvolume:
        driver: "vieux/sshfs:latest"
        driver_opts:
            allow_other: ""
            sshcmd: "<sshcmd>" 
        name: "sshvolume"

networks:
    fancynet:
```

What is the proper `docker-compose.yml` structure to have the same functionality as per cli??
