### ISSUE TITLE
Not working with docker-compose.yml

### ISSUE THREAD

**Issue by 2Kable** [vieux/docker-volume-sshfs#8]
I'm unsure with the syntax, but I'm unable to create a volume using docker-compose, it fails when mounting it to a service

```
sshvolume:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: <user>@<host>:<path-in-host>
      password: <password>

service:
      - sshvolume:<path-in-docker>
```

the command works in console:

`docker volume create -d vieux/sshfs -o sshcmd=<user>@<host>:<path-in-host> -o password=<password> --name sshvolume`

**Comment by vieux** [comment]
@2Kable I have no issue with this compose file

```
version: "3"

services:
  worker:
    image: alpine
    command: sh -c "while true; do echo \`cat /etc/hostname\` >> /data/hostnames; sleep 1; done"
    volumes:
      - sshvolume:<path-in-docker>
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role != manager]

volumes:
  sshvolume:
    driver: vieux/sshfs
    driver_opts:
      sshcmd: <user>@<host>:<path-in-host>
      password: <password>
```
